package com.example.demo.bean.po;

import java.io.Serializable;

public class PartnerContractRefunds implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_contract_refunds.refund_id
     *
     * @mbggenerated
     */
    private Integer refundId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_contract_refunds.platform_id
     *
     * @mbggenerated
     */
    private Integer platformId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_contract_refunds.purchase_id
     *
     * @mbggenerated
     */
    private Integer purchaseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_contract_refunds.amount
     *
     * @mbggenerated
     */
    private Integer amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_contract_refunds.account_type
     *
     * @mbggenerated
     */
    private Byte accountType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_contract_refunds.created
     *
     * @mbggenerated
     */
    private Integer created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_contract_refunds.updated
     *
     * @mbggenerated
     */
    private Integer updated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_contract_refunds.is_deleted
     *
     * @mbggenerated
     */
    private Byte isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_contract_refunds.account_info
     *
     * @mbggenerated
     */
    private String accountInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_contract_refunds.images
     *
     * @mbggenerated
     */
    private String images;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table partner_contract_refunds
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_contract_refunds.refund_id
     *
     * @return the value of partner_contract_refunds.refund_id
     *
     * @mbggenerated
     */
    public Integer getRefundId() {
        return refundId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_contract_refunds.refund_id
     *
     * @param refundId the value for partner_contract_refunds.refund_id
     *
     * @mbggenerated
     */
    public void setRefundId(Integer refundId) {
        this.refundId = refundId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_contract_refunds.platform_id
     *
     * @return the value of partner_contract_refunds.platform_id
     *
     * @mbggenerated
     */
    public Integer getPlatformId() {
        return platformId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_contract_refunds.platform_id
     *
     * @param platformId the value for partner_contract_refunds.platform_id
     *
     * @mbggenerated
     */
    public void setPlatformId(Integer platformId) {
        this.platformId = platformId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_contract_refunds.purchase_id
     *
     * @return the value of partner_contract_refunds.purchase_id
     *
     * @mbggenerated
     */
    public Integer getPurchaseId() {
        return purchaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_contract_refunds.purchase_id
     *
     * @param purchaseId the value for partner_contract_refunds.purchase_id
     *
     * @mbggenerated
     */
    public void setPurchaseId(Integer purchaseId) {
        this.purchaseId = purchaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_contract_refunds.amount
     *
     * @return the value of partner_contract_refunds.amount
     *
     * @mbggenerated
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_contract_refunds.amount
     *
     * @param amount the value for partner_contract_refunds.amount
     *
     * @mbggenerated
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_contract_refunds.account_type
     *
     * @return the value of partner_contract_refunds.account_type
     *
     * @mbggenerated
     */
    public Byte getAccountType() {
        return accountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_contract_refunds.account_type
     *
     * @param accountType the value for partner_contract_refunds.account_type
     *
     * @mbggenerated
     */
    public void setAccountType(Byte accountType) {
        this.accountType = accountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_contract_refunds.created
     *
     * @return the value of partner_contract_refunds.created
     *
     * @mbggenerated
     */
    public Integer getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_contract_refunds.created
     *
     * @param created the value for partner_contract_refunds.created
     *
     * @mbggenerated
     */
    public void setCreated(Integer created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_contract_refunds.updated
     *
     * @return the value of partner_contract_refunds.updated
     *
     * @mbggenerated
     */
    public Integer getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_contract_refunds.updated
     *
     * @param updated the value for partner_contract_refunds.updated
     *
     * @mbggenerated
     */
    public void setUpdated(Integer updated) {
        this.updated = updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_contract_refunds.is_deleted
     *
     * @return the value of partner_contract_refunds.is_deleted
     *
     * @mbggenerated
     */
    public Byte getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_contract_refunds.is_deleted
     *
     * @param isDeleted the value for partner_contract_refunds.is_deleted
     *
     * @mbggenerated
     */
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_contract_refunds.account_info
     *
     * @return the value of partner_contract_refunds.account_info
     *
     * @mbggenerated
     */
    public String getAccountInfo() {
        return accountInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_contract_refunds.account_info
     *
     * @param accountInfo the value for partner_contract_refunds.account_info
     *
     * @mbggenerated
     */
    public void setAccountInfo(String accountInfo) {
        this.accountInfo = accountInfo == null ? null : accountInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_contract_refunds.images
     *
     * @return the value of partner_contract_refunds.images
     *
     * @mbggenerated
     */
    public String getImages() {
        return images;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_contract_refunds.images
     *
     * @param images the value for partner_contract_refunds.images
     *
     * @mbggenerated
     */
    public void setImages(String images) {
        this.images = images == null ? null : images.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_contract_refunds
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", refundId=").append(refundId);
        sb.append(", platformId=").append(platformId);
        sb.append(", purchaseId=").append(purchaseId);
        sb.append(", amount=").append(amount);
        sb.append(", accountType=").append(accountType);
        sb.append(", created=").append(created);
        sb.append(", updated=").append(updated);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append(", accountInfo=").append(accountInfo);
        sb.append(", images=").append(images);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}