package com.example.demo.bean.po;

import java.io.Serializable;

public class PartnerContractPurchases implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_contract_purchases.purchase_id
     *
     * @mbggenerated
     */
    private Long purchaseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_contract_purchases.platform_id
     *
     * @mbggenerated
     */
    private Integer platformId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_contract_purchases.type
     *
     * @mbggenerated
     */
    private Byte type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_contract_purchases.partner_contract_id
     *
     * @mbggenerated
     */
    private Integer partnerContractId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_contract_purchases.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_contract_purchases.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_contract_purchases.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_contract_purchases.partner_id
     *
     * @mbggenerated
     */
    private Integer partnerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_contract_purchases.related_partner_id
     *
     * @mbggenerated
     */
    private Integer relatedPartnerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_contract_purchases.price
     *
     * @mbggenerated
     */
    private Integer price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_contract_purchases.platform_commission
     *
     * @mbggenerated
     */
    private Integer platformCommission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_contract_purchases.pay_method
     *
     * @mbggenerated
     */
    private Byte payMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_contract_purchases.status
     *
     * @mbggenerated
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_contract_purchases.source
     *
     * @mbggenerated
     */
    private Byte source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_contract_purchases.source_id
     *
     * @mbggenerated
     */
    private Integer sourceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_contract_purchases.refuse_reason
     *
     * @mbggenerated
     */
    private String refuseReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_contract_purchases.expire_time
     *
     * @mbggenerated
     */
    private Integer expireTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_contract_purchases.created
     *
     * @mbggenerated
     */
    private Integer created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_contract_purchases.updated
     *
     * @mbggenerated
     */
    private Integer updated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_contract_purchases.is_deleted
     *
     * @mbggenerated
     */
    private Boolean isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_contract_purchases.superior_commission
     *
     * @mbggenerated
     */
    private String superiorCommission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_contract_purchases.introducer_commission
     *
     * @mbggenerated
     */
    private String introducerCommission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_contract_purchases.pay_vouchers
     *
     * @mbggenerated
     */
    private String payVouchers;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table partner_contract_purchases
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_contract_purchases.purchase_id
     *
     * @return the value of partner_contract_purchases.purchase_id
     *
     * @mbggenerated
     */
    public Long getPurchaseId() {
        return purchaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_contract_purchases.purchase_id
     *
     * @param purchaseId the value for partner_contract_purchases.purchase_id
     *
     * @mbggenerated
     */
    public void setPurchaseId(Long purchaseId) {
        this.purchaseId = purchaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_contract_purchases.platform_id
     *
     * @return the value of partner_contract_purchases.platform_id
     *
     * @mbggenerated
     */
    public Integer getPlatformId() {
        return platformId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_contract_purchases.platform_id
     *
     * @param platformId the value for partner_contract_purchases.platform_id
     *
     * @mbggenerated
     */
    public void setPlatformId(Integer platformId) {
        this.platformId = platformId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_contract_purchases.type
     *
     * @return the value of partner_contract_purchases.type
     *
     * @mbggenerated
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_contract_purchases.type
     *
     * @param type the value for partner_contract_purchases.type
     *
     * @mbggenerated
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_contract_purchases.partner_contract_id
     *
     * @return the value of partner_contract_purchases.partner_contract_id
     *
     * @mbggenerated
     */
    public Integer getPartnerContractId() {
        return partnerContractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_contract_purchases.partner_contract_id
     *
     * @param partnerContractId the value for partner_contract_purchases.partner_contract_id
     *
     * @mbggenerated
     */
    public void setPartnerContractId(Integer partnerContractId) {
        this.partnerContractId = partnerContractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_contract_purchases.user_id
     *
     * @return the value of partner_contract_purchases.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_contract_purchases.user_id
     *
     * @param userId the value for partner_contract_purchases.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_contract_purchases.name
     *
     * @return the value of partner_contract_purchases.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_contract_purchases.name
     *
     * @param name the value for partner_contract_purchases.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_contract_purchases.phone
     *
     * @return the value of partner_contract_purchases.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_contract_purchases.phone
     *
     * @param phone the value for partner_contract_purchases.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_contract_purchases.partner_id
     *
     * @return the value of partner_contract_purchases.partner_id
     *
     * @mbggenerated
     */
    public Integer getPartnerId() {
        return partnerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_contract_purchases.partner_id
     *
     * @param partnerId the value for partner_contract_purchases.partner_id
     *
     * @mbggenerated
     */
    public void setPartnerId(Integer partnerId) {
        this.partnerId = partnerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_contract_purchases.related_partner_id
     *
     * @return the value of partner_contract_purchases.related_partner_id
     *
     * @mbggenerated
     */
    public Integer getRelatedPartnerId() {
        return relatedPartnerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_contract_purchases.related_partner_id
     *
     * @param relatedPartnerId the value for partner_contract_purchases.related_partner_id
     *
     * @mbggenerated
     */
    public void setRelatedPartnerId(Integer relatedPartnerId) {
        this.relatedPartnerId = relatedPartnerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_contract_purchases.price
     *
     * @return the value of partner_contract_purchases.price
     *
     * @mbggenerated
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_contract_purchases.price
     *
     * @param price the value for partner_contract_purchases.price
     *
     * @mbggenerated
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_contract_purchases.platform_commission
     *
     * @return the value of partner_contract_purchases.platform_commission
     *
     * @mbggenerated
     */
    public Integer getPlatformCommission() {
        return platformCommission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_contract_purchases.platform_commission
     *
     * @param platformCommission the value for partner_contract_purchases.platform_commission
     *
     * @mbggenerated
     */
    public void setPlatformCommission(Integer platformCommission) {
        this.platformCommission = platformCommission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_contract_purchases.pay_method
     *
     * @return the value of partner_contract_purchases.pay_method
     *
     * @mbggenerated
     */
    public Byte getPayMethod() {
        return payMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_contract_purchases.pay_method
     *
     * @param payMethod the value for partner_contract_purchases.pay_method
     *
     * @mbggenerated
     */
    public void setPayMethod(Byte payMethod) {
        this.payMethod = payMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_contract_purchases.status
     *
     * @return the value of partner_contract_purchases.status
     *
     * @mbggenerated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_contract_purchases.status
     *
     * @param status the value for partner_contract_purchases.status
     *
     * @mbggenerated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_contract_purchases.source
     *
     * @return the value of partner_contract_purchases.source
     *
     * @mbggenerated
     */
    public Byte getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_contract_purchases.source
     *
     * @param source the value for partner_contract_purchases.source
     *
     * @mbggenerated
     */
    public void setSource(Byte source) {
        this.source = source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_contract_purchases.source_id
     *
     * @return the value of partner_contract_purchases.source_id
     *
     * @mbggenerated
     */
    public Integer getSourceId() {
        return sourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_contract_purchases.source_id
     *
     * @param sourceId the value for partner_contract_purchases.source_id
     *
     * @mbggenerated
     */
    public void setSourceId(Integer sourceId) {
        this.sourceId = sourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_contract_purchases.refuse_reason
     *
     * @return the value of partner_contract_purchases.refuse_reason
     *
     * @mbggenerated
     */
    public String getRefuseReason() {
        return refuseReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_contract_purchases.refuse_reason
     *
     * @param refuseReason the value for partner_contract_purchases.refuse_reason
     *
     * @mbggenerated
     */
    public void setRefuseReason(String refuseReason) {
        this.refuseReason = refuseReason == null ? null : refuseReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_contract_purchases.expire_time
     *
     * @return the value of partner_contract_purchases.expire_time
     *
     * @mbggenerated
     */
    public Integer getExpireTime() {
        return expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_contract_purchases.expire_time
     *
     * @param expireTime the value for partner_contract_purchases.expire_time
     *
     * @mbggenerated
     */
    public void setExpireTime(Integer expireTime) {
        this.expireTime = expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_contract_purchases.created
     *
     * @return the value of partner_contract_purchases.created
     *
     * @mbggenerated
     */
    public Integer getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_contract_purchases.created
     *
     * @param created the value for partner_contract_purchases.created
     *
     * @mbggenerated
     */
    public void setCreated(Integer created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_contract_purchases.updated
     *
     * @return the value of partner_contract_purchases.updated
     *
     * @mbggenerated
     */
    public Integer getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_contract_purchases.updated
     *
     * @param updated the value for partner_contract_purchases.updated
     *
     * @mbggenerated
     */
    public void setUpdated(Integer updated) {
        this.updated = updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_contract_purchases.is_deleted
     *
     * @return the value of partner_contract_purchases.is_deleted
     *
     * @mbggenerated
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_contract_purchases.is_deleted
     *
     * @param isDeleted the value for partner_contract_purchases.is_deleted
     *
     * @mbggenerated
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_contract_purchases.superior_commission
     *
     * @return the value of partner_contract_purchases.superior_commission
     *
     * @mbggenerated
     */
    public String getSuperiorCommission() {
        return superiorCommission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_contract_purchases.superior_commission
     *
     * @param superiorCommission the value for partner_contract_purchases.superior_commission
     *
     * @mbggenerated
     */
    public void setSuperiorCommission(String superiorCommission) {
        this.superiorCommission = superiorCommission == null ? null : superiorCommission.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_contract_purchases.introducer_commission
     *
     * @return the value of partner_contract_purchases.introducer_commission
     *
     * @mbggenerated
     */
    public String getIntroducerCommission() {
        return introducerCommission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_contract_purchases.introducer_commission
     *
     * @param introducerCommission the value for partner_contract_purchases.introducer_commission
     *
     * @mbggenerated
     */
    public void setIntroducerCommission(String introducerCommission) {
        this.introducerCommission = introducerCommission == null ? null : introducerCommission.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_contract_purchases.pay_vouchers
     *
     * @return the value of partner_contract_purchases.pay_vouchers
     *
     * @mbggenerated
     */
    public String getPayVouchers() {
        return payVouchers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_contract_purchases.pay_vouchers
     *
     * @param payVouchers the value for partner_contract_purchases.pay_vouchers
     *
     * @mbggenerated
     */
    public void setPayVouchers(String payVouchers) {
        this.payVouchers = payVouchers == null ? null : payVouchers.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_contract_purchases
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", purchaseId=").append(purchaseId);
        sb.append(", platformId=").append(platformId);
        sb.append(", type=").append(type);
        sb.append(", partnerContractId=").append(partnerContractId);
        sb.append(", userId=").append(userId);
        sb.append(", name=").append(name);
        sb.append(", phone=").append(phone);
        sb.append(", partnerId=").append(partnerId);
        sb.append(", relatedPartnerId=").append(relatedPartnerId);
        sb.append(", price=").append(price);
        sb.append(", platformCommission=").append(platformCommission);
        sb.append(", payMethod=").append(payMethod);
        sb.append(", status=").append(status);
        sb.append(", source=").append(source);
        sb.append(", sourceId=").append(sourceId);
        sb.append(", refuseReason=").append(refuseReason);
        sb.append(", expireTime=").append(expireTime);
        sb.append(", created=").append(created);
        sb.append(", updated=").append(updated);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append(", superiorCommission=").append(superiorCommission);
        sb.append(", introducerCommission=").append(introducerCommission);
        sb.append(", payVouchers=").append(payVouchers);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}