package com.example.demo.bean.po;

import java.io.Serializable;

public class PartnerContractSnapshots implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_contract_snapshots.snapshot_id
     *
     * @mbggenerated
     */
    private Integer snapshotId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_contract_snapshots.platform_id
     *
     * @mbggenerated
     */
    private Integer platformId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_contract_snapshots.purchase_id
     *
     * @mbggenerated
     */
    private Integer purchaseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_contract_snapshots.partner_contract_id
     *
     * @mbggenerated
     */
    private Integer partnerContractId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_contract_snapshots.price
     *
     * @mbggenerated
     */
    private Integer price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_contract_snapshots.created
     *
     * @mbggenerated
     */
    private Integer created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_contract_snapshots.updated
     *
     * @mbggenerated
     */
    private Integer updated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_contract_snapshots.is_deleted
     *
     * @mbggenerated
     */
    private Byte isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_contract_snapshots.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_contract_snapshots.superior_commission
     *
     * @mbggenerated
     */
    private String superiorCommission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_contract_snapshots.introducer_commission
     *
     * @mbggenerated
     */
    private String introducerCommission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table partner_contract_snapshots
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_contract_snapshots.snapshot_id
     *
     * @return the value of partner_contract_snapshots.snapshot_id
     *
     * @mbggenerated
     */
    public Integer getSnapshotId() {
        return snapshotId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_contract_snapshots.snapshot_id
     *
     * @param snapshotId the value for partner_contract_snapshots.snapshot_id
     *
     * @mbggenerated
     */
    public void setSnapshotId(Integer snapshotId) {
        this.snapshotId = snapshotId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_contract_snapshots.platform_id
     *
     * @return the value of partner_contract_snapshots.platform_id
     *
     * @mbggenerated
     */
    public Integer getPlatformId() {
        return platformId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_contract_snapshots.platform_id
     *
     * @param platformId the value for partner_contract_snapshots.platform_id
     *
     * @mbggenerated
     */
    public void setPlatformId(Integer platformId) {
        this.platformId = platformId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_contract_snapshots.purchase_id
     *
     * @return the value of partner_contract_snapshots.purchase_id
     *
     * @mbggenerated
     */
    public Integer getPurchaseId() {
        return purchaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_contract_snapshots.purchase_id
     *
     * @param purchaseId the value for partner_contract_snapshots.purchase_id
     *
     * @mbggenerated
     */
    public void setPurchaseId(Integer purchaseId) {
        this.purchaseId = purchaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_contract_snapshots.partner_contract_id
     *
     * @return the value of partner_contract_snapshots.partner_contract_id
     *
     * @mbggenerated
     */
    public Integer getPartnerContractId() {
        return partnerContractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_contract_snapshots.partner_contract_id
     *
     * @param partnerContractId the value for partner_contract_snapshots.partner_contract_id
     *
     * @mbggenerated
     */
    public void setPartnerContractId(Integer partnerContractId) {
        this.partnerContractId = partnerContractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_contract_snapshots.price
     *
     * @return the value of partner_contract_snapshots.price
     *
     * @mbggenerated
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_contract_snapshots.price
     *
     * @param price the value for partner_contract_snapshots.price
     *
     * @mbggenerated
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_contract_snapshots.created
     *
     * @return the value of partner_contract_snapshots.created
     *
     * @mbggenerated
     */
    public Integer getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_contract_snapshots.created
     *
     * @param created the value for partner_contract_snapshots.created
     *
     * @mbggenerated
     */
    public void setCreated(Integer created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_contract_snapshots.updated
     *
     * @return the value of partner_contract_snapshots.updated
     *
     * @mbggenerated
     */
    public Integer getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_contract_snapshots.updated
     *
     * @param updated the value for partner_contract_snapshots.updated
     *
     * @mbggenerated
     */
    public void setUpdated(Integer updated) {
        this.updated = updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_contract_snapshots.is_deleted
     *
     * @return the value of partner_contract_snapshots.is_deleted
     *
     * @mbggenerated
     */
    public Byte getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_contract_snapshots.is_deleted
     *
     * @param isDeleted the value for partner_contract_snapshots.is_deleted
     *
     * @mbggenerated
     */
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_contract_snapshots.content
     *
     * @return the value of partner_contract_snapshots.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_contract_snapshots.content
     *
     * @param content the value for partner_contract_snapshots.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_contract_snapshots.superior_commission
     *
     * @return the value of partner_contract_snapshots.superior_commission
     *
     * @mbggenerated
     */
    public String getSuperiorCommission() {
        return superiorCommission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_contract_snapshots.superior_commission
     *
     * @param superiorCommission the value for partner_contract_snapshots.superior_commission
     *
     * @mbggenerated
     */
    public void setSuperiorCommission(String superiorCommission) {
        this.superiorCommission = superiorCommission == null ? null : superiorCommission.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_contract_snapshots.introducer_commission
     *
     * @return the value of partner_contract_snapshots.introducer_commission
     *
     * @mbggenerated
     */
    public String getIntroducerCommission() {
        return introducerCommission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_contract_snapshots.introducer_commission
     *
     * @param introducerCommission the value for partner_contract_snapshots.introducer_commission
     *
     * @mbggenerated
     */
    public void setIntroducerCommission(String introducerCommission) {
        this.introducerCommission = introducerCommission == null ? null : introducerCommission.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_contract_snapshots
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", snapshotId=").append(snapshotId);
        sb.append(", platformId=").append(platformId);
        sb.append(", purchaseId=").append(purchaseId);
        sb.append(", partnerContractId=").append(partnerContractId);
        sb.append(", price=").append(price);
        sb.append(", created=").append(created);
        sb.append(", updated=").append(updated);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append(", content=").append(content);
        sb.append(", superiorCommission=").append(superiorCommission);
        sb.append(", introducerCommission=").append(introducerCommission);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}