package com.example.demo.bean.po;

import java.io.Serializable;

public class PartnerContracts implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_contracts.partner_contract_id
     *
     * @mbggenerated
     */
    private Long partnerContractId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_contracts.platform_id
     *
     * @mbggenerated
     */
    private Integer platformId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_contracts.partner_id
     *
     * @mbggenerated
     */
    private Long partnerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_contracts.related_partner_id
     *
     * @mbggenerated
     */
    private Long relatedPartnerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_contracts.type
     *
     * @mbggenerated
     */
    private Byte type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_contracts.price
     *
     * @mbggenerated
     */
    private Integer price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_contracts.created
     *
     * @mbggenerated
     */
    private Integer created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_contracts.updated
     *
     * @mbggenerated
     */
    private Integer updated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_contracts.is_deleted
     *
     * @mbggenerated
     */
    private Boolean isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_contracts.superior_commission
     *
     * @mbggenerated
     */
    private String superiorCommission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_contracts.introducer_commission
     *
     * @mbggenerated
     */
    private String introducerCommission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table partner_contracts
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_contracts.partner_contract_id
     *
     * @return the value of partner_contracts.partner_contract_id
     *
     * @mbggenerated
     */
    public Long getPartnerContractId() {
        return partnerContractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_contracts.partner_contract_id
     *
     * @param partnerContractId the value for partner_contracts.partner_contract_id
     *
     * @mbggenerated
     */
    public void setPartnerContractId(Long partnerContractId) {
        this.partnerContractId = partnerContractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_contracts.platform_id
     *
     * @return the value of partner_contracts.platform_id
     *
     * @mbggenerated
     */
    public Integer getPlatformId() {
        return platformId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_contracts.platform_id
     *
     * @param platformId the value for partner_contracts.platform_id
     *
     * @mbggenerated
     */
    public void setPlatformId(Integer platformId) {
        this.platformId = platformId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_contracts.partner_id
     *
     * @return the value of partner_contracts.partner_id
     *
     * @mbggenerated
     */
    public Long getPartnerId() {
        return partnerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_contracts.partner_id
     *
     * @param partnerId the value for partner_contracts.partner_id
     *
     * @mbggenerated
     */
    public void setPartnerId(Long partnerId) {
        this.partnerId = partnerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_contracts.related_partner_id
     *
     * @return the value of partner_contracts.related_partner_id
     *
     * @mbggenerated
     */
    public Long getRelatedPartnerId() {
        return relatedPartnerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_contracts.related_partner_id
     *
     * @param relatedPartnerId the value for partner_contracts.related_partner_id
     *
     * @mbggenerated
     */
    public void setRelatedPartnerId(Long relatedPartnerId) {
        this.relatedPartnerId = relatedPartnerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_contracts.type
     *
     * @return the value of partner_contracts.type
     *
     * @mbggenerated
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_contracts.type
     *
     * @param type the value for partner_contracts.type
     *
     * @mbggenerated
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_contracts.price
     *
     * @return the value of partner_contracts.price
     *
     * @mbggenerated
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_contracts.price
     *
     * @param price the value for partner_contracts.price
     *
     * @mbggenerated
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_contracts.created
     *
     * @return the value of partner_contracts.created
     *
     * @mbggenerated
     */
    public Integer getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_contracts.created
     *
     * @param created the value for partner_contracts.created
     *
     * @mbggenerated
     */
    public void setCreated(Integer created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_contracts.updated
     *
     * @return the value of partner_contracts.updated
     *
     * @mbggenerated
     */
    public Integer getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_contracts.updated
     *
     * @param updated the value for partner_contracts.updated
     *
     * @mbggenerated
     */
    public void setUpdated(Integer updated) {
        this.updated = updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_contracts.is_deleted
     *
     * @return the value of partner_contracts.is_deleted
     *
     * @mbggenerated
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_contracts.is_deleted
     *
     * @param isDeleted the value for partner_contracts.is_deleted
     *
     * @mbggenerated
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_contracts.superior_commission
     *
     * @return the value of partner_contracts.superior_commission
     *
     * @mbggenerated
     */
    public String getSuperiorCommission() {
        return superiorCommission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_contracts.superior_commission
     *
     * @param superiorCommission the value for partner_contracts.superior_commission
     *
     * @mbggenerated
     */
    public void setSuperiorCommission(String superiorCommission) {
        this.superiorCommission = superiorCommission == null ? null : superiorCommission.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_contracts.introducer_commission
     *
     * @return the value of partner_contracts.introducer_commission
     *
     * @mbggenerated
     */
    public String getIntroducerCommission() {
        return introducerCommission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_contracts.introducer_commission
     *
     * @param introducerCommission the value for partner_contracts.introducer_commission
     *
     * @mbggenerated
     */
    public void setIntroducerCommission(String introducerCommission) {
        this.introducerCommission = introducerCommission == null ? null : introducerCommission.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_contracts
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", partnerContractId=").append(partnerContractId);
        sb.append(", platformId=").append(platformId);
        sb.append(", partnerId=").append(partnerId);
        sb.append(", relatedPartnerId=").append(relatedPartnerId);
        sb.append(", type=").append(type);
        sb.append(", price=").append(price);
        sb.append(", created=").append(created);
        sb.append(", updated=").append(updated);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append(", superiorCommission=").append(superiorCommission);
        sb.append(", introducerCommission=").append(introducerCommission);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}