package com.example.demo.pojo;

import java.io.Serializable;

public class ErpPurchaseMaterialReviseBills implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_purchase_material_revise_bills.material_revise_bill_id
     *
     * @mbggenerated
     */
    private Integer materialReviseBillId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_purchase_material_revise_bills.erp_id
     *
     * @mbggenerated
     */
    private Integer erpId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_purchase_material_revise_bills.property_id
     *
     * @mbggenerated
     */
    private Integer propertyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_purchase_material_revise_bills.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_purchase_material_revise_bills.revise_date
     *
     * @mbggenerated
     */
    private Integer reviseDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_purchase_material_revise_bills.supplier_id
     *
     * @mbggenerated
     */
    private Integer supplierId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_purchase_material_revise_bills.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_purchase_material_revise_bills.confirmation_code
     *
     * @mbggenerated
     */
    private String confirmationCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_purchase_material_revise_bills.print_count
     *
     * @mbggenerated
     */
    private Integer printCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_purchase_material_revise_bills.update_code
     *
     * @mbggenerated
     */
    private String updateCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_purchase_material_revise_bills.transmission_code
     *
     * @mbggenerated
     */
    private String transmissionCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_purchase_material_revise_bills.created
     *
     * @mbggenerated
     */
    private Integer created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_purchase_material_revise_bills.updated
     *
     * @mbggenerated
     */
    private Integer updated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_purchase_material_revise_bills.is_deleted
     *
     * @mbggenerated
     */
    private Byte isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table erp_purchase_material_revise_bills
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_purchase_material_revise_bills.material_revise_bill_id
     *
     * @return the value of erp_purchase_material_revise_bills.material_revise_bill_id
     *
     * @mbggenerated
     */
    public Integer getMaterialReviseBillId() {
        return materialReviseBillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_purchase_material_revise_bills.material_revise_bill_id
     *
     * @param materialReviseBillId the value for erp_purchase_material_revise_bills.material_revise_bill_id
     *
     * @mbggenerated
     */
    public void setMaterialReviseBillId(Integer materialReviseBillId) {
        this.materialReviseBillId = materialReviseBillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_purchase_material_revise_bills.erp_id
     *
     * @return the value of erp_purchase_material_revise_bills.erp_id
     *
     * @mbggenerated
     */
    public Integer getErpId() {
        return erpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_purchase_material_revise_bills.erp_id
     *
     * @param erpId the value for erp_purchase_material_revise_bills.erp_id
     *
     * @mbggenerated
     */
    public void setErpId(Integer erpId) {
        this.erpId = erpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_purchase_material_revise_bills.property_id
     *
     * @return the value of erp_purchase_material_revise_bills.property_id
     *
     * @mbggenerated
     */
    public Integer getPropertyId() {
        return propertyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_purchase_material_revise_bills.property_id
     *
     * @param propertyId the value for erp_purchase_material_revise_bills.property_id
     *
     * @mbggenerated
     */
    public void setPropertyId(Integer propertyId) {
        this.propertyId = propertyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_purchase_material_revise_bills.code
     *
     * @return the value of erp_purchase_material_revise_bills.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_purchase_material_revise_bills.code
     *
     * @param code the value for erp_purchase_material_revise_bills.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_purchase_material_revise_bills.revise_date
     *
     * @return the value of erp_purchase_material_revise_bills.revise_date
     *
     * @mbggenerated
     */
    public Integer getReviseDate() {
        return reviseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_purchase_material_revise_bills.revise_date
     *
     * @param reviseDate the value for erp_purchase_material_revise_bills.revise_date
     *
     * @mbggenerated
     */
    public void setReviseDate(Integer reviseDate) {
        this.reviseDate = reviseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_purchase_material_revise_bills.supplier_id
     *
     * @return the value of erp_purchase_material_revise_bills.supplier_id
     *
     * @mbggenerated
     */
    public Integer getSupplierId() {
        return supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_purchase_material_revise_bills.supplier_id
     *
     * @param supplierId the value for erp_purchase_material_revise_bills.supplier_id
     *
     * @mbggenerated
     */
    public void setSupplierId(Integer supplierId) {
        this.supplierId = supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_purchase_material_revise_bills.remark
     *
     * @return the value of erp_purchase_material_revise_bills.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_purchase_material_revise_bills.remark
     *
     * @param remark the value for erp_purchase_material_revise_bills.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_purchase_material_revise_bills.confirmation_code
     *
     * @return the value of erp_purchase_material_revise_bills.confirmation_code
     *
     * @mbggenerated
     */
    public String getConfirmationCode() {
        return confirmationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_purchase_material_revise_bills.confirmation_code
     *
     * @param confirmationCode the value for erp_purchase_material_revise_bills.confirmation_code
     *
     * @mbggenerated
     */
    public void setConfirmationCode(String confirmationCode) {
        this.confirmationCode = confirmationCode == null ? null : confirmationCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_purchase_material_revise_bills.print_count
     *
     * @return the value of erp_purchase_material_revise_bills.print_count
     *
     * @mbggenerated
     */
    public Integer getPrintCount() {
        return printCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_purchase_material_revise_bills.print_count
     *
     * @param printCount the value for erp_purchase_material_revise_bills.print_count
     *
     * @mbggenerated
     */
    public void setPrintCount(Integer printCount) {
        this.printCount = printCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_purchase_material_revise_bills.update_code
     *
     * @return the value of erp_purchase_material_revise_bills.update_code
     *
     * @mbggenerated
     */
    public String getUpdateCode() {
        return updateCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_purchase_material_revise_bills.update_code
     *
     * @param updateCode the value for erp_purchase_material_revise_bills.update_code
     *
     * @mbggenerated
     */
    public void setUpdateCode(String updateCode) {
        this.updateCode = updateCode == null ? null : updateCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_purchase_material_revise_bills.transmission_code
     *
     * @return the value of erp_purchase_material_revise_bills.transmission_code
     *
     * @mbggenerated
     */
    public String getTransmissionCode() {
        return transmissionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_purchase_material_revise_bills.transmission_code
     *
     * @param transmissionCode the value for erp_purchase_material_revise_bills.transmission_code
     *
     * @mbggenerated
     */
    public void setTransmissionCode(String transmissionCode) {
        this.transmissionCode = transmissionCode == null ? null : transmissionCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_purchase_material_revise_bills.created
     *
     * @return the value of erp_purchase_material_revise_bills.created
     *
     * @mbggenerated
     */
    public Integer getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_purchase_material_revise_bills.created
     *
     * @param created the value for erp_purchase_material_revise_bills.created
     *
     * @mbggenerated
     */
    public void setCreated(Integer created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_purchase_material_revise_bills.updated
     *
     * @return the value of erp_purchase_material_revise_bills.updated
     *
     * @mbggenerated
     */
    public Integer getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_purchase_material_revise_bills.updated
     *
     * @param updated the value for erp_purchase_material_revise_bills.updated
     *
     * @mbggenerated
     */
    public void setUpdated(Integer updated) {
        this.updated = updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_purchase_material_revise_bills.is_deleted
     *
     * @return the value of erp_purchase_material_revise_bills.is_deleted
     *
     * @mbggenerated
     */
    public Byte getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_purchase_material_revise_bills.is_deleted
     *
     * @param isDeleted the value for erp_purchase_material_revise_bills.is_deleted
     *
     * @mbggenerated
     */
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_purchase_material_revise_bills
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", materialReviseBillId=").append(materialReviseBillId);
        sb.append(", erpId=").append(erpId);
        sb.append(", propertyId=").append(propertyId);
        sb.append(", code=").append(code);
        sb.append(", reviseDate=").append(reviseDate);
        sb.append(", supplierId=").append(supplierId);
        sb.append(", remark=").append(remark);
        sb.append(", confirmationCode=").append(confirmationCode);
        sb.append(", printCount=").append(printCount);
        sb.append(", updateCode=").append(updateCode);
        sb.append(", transmissionCode=").append(transmissionCode);
        sb.append(", created=").append(created);
        sb.append(", updated=").append(updated);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}