package com.example.demo.dao;

import java.util.List;

import com.example.demo.bean.po.ErpPurchaseMaterialReviseBills;

public interface ErpPurchaseMaterialReviseBillsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_purchase_material_revise_bills
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer materialReviseBillId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_purchase_material_revise_bills
     *
     * @mbggenerated
     */
    int insert(ErpPurchaseMaterialReviseBills record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_purchase_material_revise_bills
     *
     * @mbggenerated
     */
    ErpPurchaseMaterialReviseBills selectByPrimaryKey(Integer materialReviseBillId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_purchase_material_revise_bills
     *
     * @mbggenerated
     */
    List<ErpPurchaseMaterialReviseBills> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_purchase_material_revise_bills
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ErpPurchaseMaterialReviseBills record);
}