package com.example.demo.dao;

import java.util.List;

import com.example.demo.bean.po.PartnerShops;

public interface PartnerShopsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_shops
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_shops
     *
     * @mbggenerated
     */
    int insert(PartnerShops record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_shops
     *
     * @mbggenerated
     */
    PartnerShops selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_shops
     *
     * @mbggenerated
     */
    List<PartnerShops> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_shops
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PartnerShops record);
}