package com.example.demo.dao;

import java.util.List;

import com.example.demo.bean.po.PartnerContractSnapshots;

public interface PartnerContractSnapshotsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_contract_snapshots
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer snapshotId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_contract_snapshots
     *
     * @mbggenerated
     */
    int insert(PartnerContractSnapshots record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_contract_snapshots
     *
     * @mbggenerated
     */
    PartnerContractSnapshots selectByPrimaryKey(Integer snapshotId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_contract_snapshots
     *
     * @mbggenerated
     */
    List<PartnerContractSnapshots> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_contract_snapshots
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PartnerContractSnapshots record);
}