package com.example.demo.dao;

import java.util.List;

import com.example.demo.bean.po.PartnerUserBinds;

public interface PartnerUserBindsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_user_binds
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_user_binds
     *
     * @mbggenerated
     */
    int insert(PartnerUserBinds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_user_binds
     *
     * @mbggenerated
     */
    PartnerUserBinds selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_user_binds
     *
     * @mbggenerated
     */
    List<PartnerUserBinds> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_user_binds
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PartnerUserBinds record);
}