package com.example.demo.dao;

import java.util.List;

import com.example.demo.bean.po.PartnerContractRefunds;

public interface PartnerContractRefundsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_contract_refunds
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer refundId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_contract_refunds
     *
     * @mbggenerated
     */
    int insert(PartnerContractRefunds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_contract_refunds
     *
     * @mbggenerated
     */
    PartnerContractRefunds selectByPrimaryKey(Integer refundId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_contract_refunds
     *
     * @mbggenerated
     */
    List<PartnerContractRefunds> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_contract_refunds
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PartnerContractRefunds record);
}