package com.example.demo.dao;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

import com.example.demo.bean.po.PartnerContracts;

@Repository
@Mapper
public interface PartnerContractsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_contracts
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long partnerContractId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_contracts
     *
     * @mbggenerated
     */
    int insert(PartnerContracts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_contracts
     *
     * @mbggenerated
     */
    PartnerContracts selectByPrimaryKey(Long partnerContractId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_contracts
     *
     * @mbggenerated
     */
    List<PartnerContracts> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_contracts
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PartnerContracts record);
}