package com.example.demo.dao;

import com.example.demo.bean.po.Partners;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Repository
@Mapper
public interface PartnersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partners
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer partnerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partners
     *
     * @mbggenerated
     */
    int insert(Partners record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partners
     *
     * @mbggenerated
     */
    Partners selectByPrimaryKey(Integer partnerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partners
     *
     * @mbggenerated
     */
    List<Partners> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partners
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Partners record);
}