package com.example.demo.dao;

import java.util.List;

import com.example.demo.bean.po.PartnerContractTemplates;

public interface PartnerContractTemplatesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_contract_templates
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer templateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_contract_templates
     *
     * @mbggenerated
     */
    int insert(PartnerContractTemplates record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_contract_templates
     *
     * @mbggenerated
     */
    PartnerContractTemplates selectByPrimaryKey(Integer templateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_contract_templates
     *
     * @mbggenerated
     */
    List<PartnerContractTemplates> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_contract_templates
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PartnerContractTemplates record);
}