package com.example.demo.dao;

import java.util.List;

import com.example.demo.bean.po.PartnerContracts;

public interface PartnerContractsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_contracts
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long partnerContractId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_contracts
     *
     * @mbggenerated
     */
    int insert(PartnerContracts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_contracts
     *
     * @mbggenerated
     */
    PartnerContracts selectByPrimaryKey(Long partnerContractId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_contracts
     *
     * @mbggenerated
     */
    List<PartnerContracts> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_contracts
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PartnerContracts record);
}